pipeline: selection_pressure_pipeline
reason: ""
cores: 8
log_dir: logs
run_id: example_run
protein_name: selection_batch
env_dir: bin/envs

PROTEINS: [ExampleProtein]
PROTEIN_FILE: database/collated/.../protein_file.csv
GENOME_FILE: database/collated/.../genome_file.csv
CDS_FILES_PATH: database/collated/.../cds
itol_project: Asgard
