pipeline: synteny_pipeline
reason: ""
cores: 8
log_dir: logs
run_id: example_run
protein_name: ExampleProtein
env_dir: bin/envs

from_existing_folder: false
from_database: true

genome_file: database/collated/.../genome_file.csv
interproscan_file: database/collated/.../interproscan.parquet
interproscan_full: database/collated/.../interproscan_full.parquet
gbk_database: database/collated/.../gbk

gene_neighborhood_protein_sets: [ExampleProtein]
taxa_levels: [class]
synteny_plot_genomes: [GCF_000000000.1]
