pipeline: updation
reason: ""
cores: 4
log_dir: logs
run_id: example_run
env_dir: bin/envs

output_dir: database/collated/latest_update
organisms:
  - name: "Asgard archaea"
    taxon: 1935183
    assembly_level: [Complete Genome]
    refseq_only: true
